### ISSUE TITLE
Flaps are not annimated

### ISSUE THREAD

**Issue by IAHM-COL** [FGMEMBERS/b29#1]
I found in my latest test that flaps are not animated, and I certainly do not know whether they are having any effect on the FDM yet.  I am testing JSBSIM

**Comment by JWocky** [comment]
Hi Israel,

the flaps are animated, but in a weird way, I didn't repair it because I 
ran out of time. Press [ and hold it ... and yes, it sucks.
Black square -> not nice too.
And yes, I tested her without sound ... seems, it needs a little push 
there too ...
She worked okay here, not great when it came to balance, so can you 
define "trouble"? Swinging, not climbing, what?

Long story short, I have next time to drive to the grocery or no food at 
the Tour, then some other things to do, then I get on Mumble and look 
into the b29 again

Peter

**Comment by IAHM-COL** [comment]
Oh ok.
Hold not tap [   ]

It works. Thanks

**Comment by JWocky** [comment]
I have an idea where that hangs. After lunch and grocery, I look for it 
(it bothered me already yesterday, but I had no time left)

**Comment by IAHM-COL** [comment]
Behavior of flaps corrected  by JWocky with f4de5491e448611841411b54ad6fbdbd677ca72a
